"""empty message

Revision ID: 2f4eb3a501e2
Revises: outbox_events
Create Date: 2026-07-13 10:57:29.367828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f4eb3a501e2'
down_revision: Union[str, None] = 'outbox_events'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 注：outbox_events 和 dict 表是项目核心表，保留不删。
    # 以下只修正 slides / oss_configs / devices 的 comment 与索引重命名。
    op.alter_column('devices', 'dept_id',
               existing_type=sa.INTEGER(),
               comment='部门ID（引用 core-service auth_departments.id）',
               existing_nullable=True)
    op.alter_column('oss_configs', 'app_code',
               existing_type=sa.VARCHAR(length=32),
               comment='应用编码，用于路由存储',
               existing_nullable=False)
    op.alter_column('oss_configs', 'config_name',
               existing_type=sa.VARCHAR(length=128),
               comment='配置名称',
               existing_nullable=False)
    op.alter_column('oss_configs', 'bucket_name',
               existing_type=sa.VARCHAR(length=128),
               comment='Bucket 名称',
               existing_nullable=False)
    op.alter_column('oss_configs', 'is_default',
               existing_type=sa.BOOLEAN(),
               comment='是否默认配置',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('oss_configs', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='是否启用',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('oss_configs', 'created_by',
               existing_type=sa.INTEGER(),
               comment='创建人 user_id',
               existing_nullable=False)
    op.alter_column('slides', 'id',
               existing_type=sa.INTEGER(),
               comment='主键 ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('slides', 'app_code',
               existing_type=sa.VARCHAR(length=32),
               comment='应用编码，路由到对应 Bucket 配置',
               existing_nullable=False)
    op.alter_column('slides', 'device_id',
               existing_type=sa.INTEGER(),
               comment='关联设备 ID（devices.id）',
               existing_nullable=True)
    op.alter_column('slides', 'batch_id',
               existing_type=sa.VARCHAR(length=64),
               comment='批次 ID，同批次文件共享（UUID hex）',
               existing_nullable=True)
    op.alter_column('slides', 'relative_path',
               existing_type=sa.VARCHAR(length=512),
               comment='文件在文件夹中的相对路径（DZI/LD 场景使用）',
               existing_nullable=True)
    op.alter_column('slides', 'slide_code',
               existing_type=sa.VARCHAR(length=255),
               comment='切片编码（对应扫描仪 barcode）',
               existing_nullable=False)
    op.alter_column('slides', 'file_format',
               existing_type=sa.VARCHAR(length=16),
               comment='文件格式：SVS/TIFF/TIF/DZI/LD（DZI/LD 为文件夹格式）',
               existing_nullable=False)
    op.alter_column('slides', 'staining_type',
               existing_type=sa.VARCHAR(length=32),
               comment='染色类型：HE/IHC/PAS/Masson 等',
               existing_nullable=True)
    op.alter_column('slides', 'file_size',
               existing_type=sa.INTEGER(),
               comment='文件大小（字节）',
               existing_nullable=False)
    op.alter_column('slides', 'oss_key',
               existing_type=sa.VARCHAR(length=512),
               comment='OSS 路径：单文件指向文件，LD/DZI 指向目录',
               existing_nullable=True)
    op.alter_column('slides', 'thumbnail_key',
               existing_type=sa.VARCHAR(length=512),
               comment='缩略图 OSS 路径（可选）',
               existing_nullable=True)
    op.alter_column('slides', 'status',
               existing_type=sa.VARCHAR(length=16),
               comment='状态：pending/uploading/ready/error',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('slides', 'uploaded_by',
               existing_type=sa.INTEGER(),
               comment='上传人 ID（设备上传时为 device_id）',
               existing_nullable=False)
    op.alter_column('slides', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('slides', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_slice_files_app_case'), table_name='slides')
    op.drop_index(op.f('ix_slice_files_app_patient'), table_name='slides')
    op.drop_index(op.f('ix_slice_files_batch_id'), table_name='slides')
    op.drop_index(op.f('ix_slice_files_status'), table_name='slides')
    op.create_index(op.f('ix_slides_batch_id'), 'slides', ['batch_id'], unique=False)
    op.create_index(op.f('ix_slides_status'), 'slides', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slides_status'), table_name='slides')
    op.drop_index(op.f('ix_slides_batch_id'), table_name='slides')
    op.create_index(op.f('ix_slice_files_status'), 'slides', ['status'], unique=False)
    op.create_index(op.f('ix_slice_files_batch_id'), 'slides', ['batch_id'], unique=False)
    op.create_index(op.f('ix_slice_files_app_patient'), 'slides', ['app_code'], unique=False)
    op.create_index(op.f('ix_slice_files_app_case'), 'slides', ['app_code'], unique=False)
    op.alter_column('slides', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('slides', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('slides', 'uploaded_by',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='上传人 ID（设备上传时为 device_id）',
               existing_nullable=False)
    op.alter_column('slides', 'status',
               existing_type=sa.VARCHAR(length=16),
               comment=None,
               existing_comment='状态：pending/uploading/ready/error',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('slides', 'thumbnail_key',
               existing_type=sa.VARCHAR(length=512),
               comment=None,
               existing_comment='缩略图 OSS 路径（可选）',
               existing_nullable=True)
    op.alter_column('slides', 'oss_key',
               existing_type=sa.VARCHAR(length=512),
               comment=None,
               existing_comment='OSS 路径：单文件指向文件，LD/DZI 指向目录',
               existing_nullable=True)
    op.alter_column('slides', 'file_size',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='文件大小（字节）',
               existing_nullable=False)
    op.alter_column('slides', 'staining_type',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='染色类型：HE/IHC/PAS/Masson 等',
               existing_nullable=True)
    op.alter_column('slides', 'file_format',
               existing_type=sa.VARCHAR(length=16),
               comment=None,
               existing_comment='文件格式：SVS/TIFF/TIF/DZI/LD（DZI/LD 为文件夹格式）',
               existing_nullable=False)
    op.alter_column('slides', 'slide_code',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='切片编码（对应扫描仪 barcode）',
               existing_nullable=False)
    op.alter_column('slides', 'relative_path',
               existing_type=sa.VARCHAR(length=512),
               comment=None,
               existing_comment='文件在文件夹中的相对路径（DZI/LD 场景使用）',
               existing_nullable=True)
    op.alter_column('slides', 'batch_id',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='批次 ID，同批次文件共享（UUID hex）',
               existing_nullable=True)
    op.alter_column('slides', 'device_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='关联设备 ID（devices.id）',
               existing_nullable=True)
    op.alter_column('slides', 'app_code',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='应用编码，路由到对应 Bucket 配置',
               existing_nullable=False)
    op.alter_column('slides', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='主键 ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('oss_configs', 'created_by',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='创建人 user_id',
               existing_nullable=False)
    op.alter_column('oss_configs', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否启用',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('oss_configs', 'is_default',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否默认配置',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('oss_configs', 'bucket_name',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='Bucket 名称',
               existing_nullable=False)
    op.alter_column('oss_configs', 'config_name',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='配置名称',
               existing_nullable=False)
    op.alter_column('oss_configs', 'app_code',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='应用编码，用于路由存储',
               existing_nullable=False)
    op.alter_column('devices', 'dept_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='部门ID（引用 core-service auth_departments.id）',
               existing_nullable=True)
    # 注：outbox_events / dict_types / dict_values 表在 upgrade 中保留未动，
    # downgrade 无需重建。
    # ### end Alembic commands ###
